//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramFollowers.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follower_view
    {
        public int ID_Follower { get; set; }
        public string Follower_Name { get; set; }
        public Nullable<int> ID_User { get; set; }
        public byte[] Follower_version { get; set; }
    }
}
