//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramFollowers.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribed
    {
        public int iD_Subscribed { get; set; }
        public string Sub_Name { get; set; }
        public Nullable<int> ID_Follower { get; set; }
    
        public virtual Follower Follower { get; set; }
    }
}
