//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramFollowers.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unsubscribed
    {
        public int Id_Unsubscribed { get; set; }
        public string Unsub_Name { get; set; }
        public Nullable<int> Id_Followers { get; set; }
    
        public virtual Followers Followers { get; set; }
    }
}
